name: tests 
on:
  push:
    branches:
    - master
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: cd src/frontend
    - run: npm install
    - run: npm test
