stages:
  - build
  - test

image: tiangolo/uvicorn-gunicorn-fastapi:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps aux
    - ps aux | grep -i uvicorn

