stages:
  - build
  - test

image: beevelop/nodejs-python:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9

test:
  stage: test
  script:
    - cd src/backend
    - pip install -r requirements.txt
    - npm install -g newman
    - newman --version
    - uvicorn server:app &
    - sleep 20
    - ps aux
    - ps aux | grep -i "[u]vicorn" 
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'}
    - cd ../tests/postman
    - newman run fyp.postman_collection.json
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9
