stages:
  - build
  - test

image: tiangolo/uvicorn-gunicorn-fastapi:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9

postman_tests:
  stage: test
  image: 
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - cd src/tests/postman
    - newman --version
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9
    - ps aux
    - newman run status.postman_collection.json --reporters cli


