stages:
  - build
  - test

image: tiangolo/uvicorn-gunicorn-fastapi:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    # Commented out temporarily
    # - uvicorn server:app --reload
