stages:
  - build
  - test

image: postman/newman:5-alpine

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9

