stages:
  - build
  - test

image: tiangolo/uvicorn-gunicorn-fastapi:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - uvicorn server:app --reload
    - ps aux
    - ps aux | grep -i firefoxps aux | grep -i uvicorn

