stages:
  - build
  - test

image: tiangolo/uvicorn-gunicorn-fastapi:latest

build_project:
  stage: build
  script:
    - cd src/backend
    - python -V
    - pip install -r requirements.txt
    - uvicorn server:app &
    - ps ax
    - ps aux | grep -i "[u]vicorn"
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'}
    - ps aux | grep -i "[u]vicorn" | awk {'print $2'} | xargs kill -9
    - ps ax

