name: test 
on:
  push:
    branches:
    - master
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: install frontend dependencies
      working-directory: ./src/frontend
      run: npm install
    - name: run tests
      working-directory: ./src/frontend
      run: npm test
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: install Python dependencies
      working-directory: ./src/backend
      run: pip install -r requirements.txt
    - name: run unit tests
      working-directory: ./src/backend/tests/unit-tests
      run: python -m unittest
